=== akavadim/HSE_apps/Курс 2/КПО/Lab4/plan.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.myschema.ru">
  <xs:element name="Schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Day" minOccurs="0" maxOccurs="7">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DayName">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Monday" />
                    <xs:enumeration value="Tuesday"/>
                    <xs:enumeration value="Wednesday" />
                    <xs:enumeration value="Thursday"/>
                    <xs:enumeration value="Friday"/>
                    <xs:enumeration value="Saturday"/>
                    <xs:enumeration value="Sunday"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Subjects" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Subject" minOccurs="1" maxOccurs="4">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" type="xs:string" />
                          <xs:element name="LectureHall" type="xs:string" />
                          <xs:element name="Teacher" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:pattern value="[a-zA-Zа-яА-Я]+ [a-zA-Zа-яА-Я].[ ]?[a-zA-Zа-яА-Я]."/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="Type">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Seminar" />
                                <xs:enumeration value="Lecture"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="StartTime" type="xs:time" />
                          <xs:element name="EndTime" type="xs:time" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== akavadim/HSE_apps/Курс 2/КПО/Lab4/Test/Test/bin/Debug/netcoreapp3.1/plan.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Schedule[
  <!ELEMENT Schedule (Day*)>
  <!ELEMENT Day (DayName, Subjects?)>
  <!ELEMENT DayName (#PCDATA)>
  <!ELEMENT Subjects (Subject+)>
  <!ELEMENT Subject (Name, LectureHall, Teacher, Type, StartTime, EndTime)>
  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT LectureHall (#PCDATA)>
  <!ELEMENT Teacher (#PCDATA)>
  <!ELEMENT Type (#PCDATA)>
  <!ELEMENT StartTime (#PCDATA)>
  <!ELEMENT EndTime (#PCDATA)>
]>
<Schedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.myschema.ru plan.xsd">
  <Day>
    <DayName>Monday</DayName>
    <Subjects>
      <Subject>
        <Name>Английский</Name>
        <LectureHall>110</LectureHall>
        <Teacher>Садикова Т.Б.</Teacher>
        <Type>Seminar</Type>
        <StartTime>08:10:00</StartTime>
        <EndTime>09:30:00</EndTime>
      </Subject>
      <Subject>
        <Name>Английский</Name>
        <LectureHall>110</LectureHall>
        <Teacher>Садикова Т.Б.</Teacher>
        <Type>Seminar</Type>
        <StartTime>09:40:00</StartTime>
        <EndTime>11:00:00</EndTime>
      </Subject>
      <Subject>
        <Name>Алгоритмы и структуры данных</Name>
        <LectureHall>504</LectureHall>
        <Teacher>Морозенко В.В.</Teacher>
        <Type>Seminar</Type>
        <StartTime>11:30:00</StartTime>
        <EndTime>12:50:00</EndTime>
      </Subject>
    </Subjects>
  </Day>
  <Day>
    <DayName>Tuesday</DayName>
    <Subjects>
      <Subject>
        <Name>Базы данных</Name>
        <LectureHall>510</LectureHall>
        <Teacher>Хренов В.В.</Teacher>
        <Type>Seminar</Type>
        <StartTime>11:30:00</StartTime>
        <EndTime>12:50:00</EndTime>
      </Subject>
      <Subject>
        <Name>Конструирование программ. обеспечения</Name>
        <LectureHall>102</LectureHall>
        <Teacher>Ланин В.В.</Teacher>
        <Type>Lecture</Type>
        <StartTime>13:00:00</StartTime>
        <EndTime>14:20:00</EndTime>
      </Subject>
    </Subjects>
  </Day>
  <Day>
    <DayName>Wednesday</DayName>
    <Subjects>
      <Subject>
        <Name>Конструирование программ. обеспечения</Name>
        <LectureHall>509</LectureHall>
        <Teacher>Ланин В.В.</Teacher>
        <Type>Seminar</Type>
        <StartTime>09:40:00</StartTime>
        <EndTime>11:00:00</EndTime>
      </Subject>
      <Subject>
        <Name>Операционные системы</Name>
        <LectureHall>305</LectureHall>
        <Teacher>Ланин В.В.</Teacher>
        <Type>Seminar</Type>
        <StartTime>11:30:00</StartTime>
        <EndTime>12:50:00</EndTime>
      </Subject>
      <Subject>
        <Name>Стат. и эмпер. методы компьютинга</Name>
        <LectureHall>511</LectureHall>
        <Teacher>Радионова М.В.</Teacher>
        <Type>Seminar</Type>
        <StartTime>13:00:00</StartTime>
        <EndTime>14:20:00</EndTime>
      </Subject>
    </Subjects>
  </Day>
  <Day>
    <DayName>Thursday</DayName>
    <Subjects>
      <Subject>
        <Name>Операционные системы</Name>
        <LectureHall>216</LectureHall>
        <Teacher>Лядова Л.Н.</Teacher>
        <Type>Lecture</Type>
        <StartTime>11:30:00</StartTime>
        <EndTime>12:50:00</EndTime>
      </Subject>
      <Subject>
        <Name>Стат.и эмп. методы компьютинга</Name>
        <LectureHall>216</LectureHall>
        <Teacher>Радионова М.В.</Teacher>
        <Type>Lecture</Type>
        <StartTime>13:00:00</StartTime>
        <EndTime>14:20:00</EndTime>
      </Subject>
    </Subjects>
  </Day>
  <Day>
    <DayName>Friday</DayName>
    <Subjects>
      <Subject>
        <Name>Науч.- исслед. семинар</Name>
        <LectureHall>102</LectureHall>
        <Teacher>Носкова Е.Н.</Teacher>
        <Type>Seminar</Type>
        <StartTime>09:40:00</StartTime>
        <EndTime>11:00:00</EndTime>
      </Subject>
      <Subject>
        <Name>Базы данных</Name>
        <LectureHall>102</LectureHall>
        <Teacher>Хренов В.В.</Teacher>
        <Type>Lecture</Type>
        <StartTime>11:30:00</StartTime>
        <EndTime>12:50:00</EndTime>
      </Subject>
    </Subjects>
  </Day>
</Schedule>
